# Generated by Django 4.0.5 on 2022-07-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hollywood_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=50)),
                ('category', models.TextField()),
                ('rating', models.FloatField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='homepage_movies',
            fields=[
                ('movie_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('links', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('rating', models.FloatField(max_length=2)),
                ('quality', models.CharField(max_length=4)),
                ('age', models.CharField(max_length=5)),
                ('new', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('movieid', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='myapp.homepage_movies')),
            ],
        ),
    ]
