# Generated by Django 4.0.5 on 2022-07-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage_movies',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='homepage_movies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Popularity',
        ),
    ]
