# Generated by Django 4.0.5 on 2022-07-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_homepage_movies_new_homepage_movies_trailer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage_movies',
            old_name='links',
            new_name='download_link',
        ),
    ]
