# Generated by Django 4.0.5 on 2022-06-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_movies_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Rating',
            new_name='rating',
        ),
    ]
