# Generated by Django 4.0.5 on 2022-07-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_links_homepage_movies_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_movies',
            name='country',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage_movies',
            name='release_year',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
