# Generated by Django 4.0.5 on 2022-06-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_movies_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepage_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('links', models.TextField()),
                ('type1', models.TextField()),
                ('type2', models.TextField()),
                ('rating', models.FloatField(max_length=2)),
                ('quality', models.TextField()),
                ('age', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='movies',
        ),
    ]
