# Generated by Django 4.0.5 on 2022-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_homepage_movies_delete_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_movies',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
