# Generated by Django 4.0.5 on 2022-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_homepage_movies_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_movies',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
