# Generated by Django 4.0.5 on 2022-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_homepage_movies_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='hollywood_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=30)),
                ('category', models.TextField()),
                ('rating', models.FloatField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='homepage_movies',
            old_name='type1',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='homepage_movies',
            name='type2',
        ),
    ]
