# Generated by Django 4.0.5 on 2022-07-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_hollywood_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hollywood_movies',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
